name: chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  shared_preferences: ^2.2.2
  google_sign_in: ^7.2.0
  connectivity_plus: ^7.0.0
  firebase_auth: ^6.1.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  intl: ^0.20.2
  get: ^4.7.3
  crypto: ^3.0.7
  agora_rtc_engine: ^6.5.3
  permission_handler: ^12.0.1
  firebase_messaging: ^16.1.0
  lottie: ^3.3.2
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/MetroUI_Messaging.webp
    - assets/anim/loading.json
    - assets/anim/Phoenix Dancing.json
    # - assets/image/google_logo.png  # Uncomment and ensure this file exists if you want to use it


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/chat-app-icon-24.jpg"


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android_gravity: center
  android: true
  ios: true
