name: chat_setup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  cloud_firestore: ^6.1.1
  flutter_sound: ^9.30.0
  firebase_storage: ^13.0.5
  camera: ^0.11.3
  image_picker: ^1.2.1
  crypto: ^3.0.7
  animated_text_kit: ^4.3.0
  lottie: ^3.3.2
  shared_preferences: ^2.5.4
  agora_rtc_engine: ^6.5.3
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  rename: ^3.1.0
  google_sign_in: 6.2.1
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/anim/
    - assets/image/


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/logo.png"


flutter_native_splash:
  color: "#F6F7F9"
  color_dark: "#000000"

  image: assets/image/logo.png
  image_dark: assets/image/logo.png

  android: true
  ios: true

  android_12:
    color: "#F6F7F9"
    image: assets/image/logo.png
